from .arknights import ArknightsOperation
from .start import StartOperation
from .wake import WakeOperation
from .mail import MailOperation
from .receiving_mail import ReceivingMailOperation
from .delete_mail import DeleteMailOperation
from .quit_mail import QuitMailOperation
from .infrastructure import InfrastructureOperation
from .infrastructure_tips import InfrastructureTipsOperation
from .material_receipt import MaterialReceiptOperation
from .lmb_receipt import LmbReceiptOperation