from .arknights import ArknightsOperation
from .start import StartOperation
from .wake import WakeOperation
from .mail import MailOperation
from .receiving_mail import ReceivingMailOperation
from .collect import CollectOperation
from .delete_mail import DeleteMailOperation
from .quit_mail import QuitMailOperation
from .infrastructure import InfrastructureOperation
from .infrastructure_tips import InfrastructureTipsOperation
from .material_receipt import MaterialReceiptOperation
from .lmb_receipt import LmbReceiptOperation
from .operators_trust import OperatorsTrustOperation
from .clue_gathering import ClueGatheringOperation
from .reception import ReceptionOperationOCR
from .collecting_clues import CollectingCluesOperation
from .reception_clues import ReceptionCluesOperation
from .gather_reception_clues import GatherReceptionCluesOperation
from .returns import ReturnOperation
from .confirm import ConfirmOperation